fix: 修复 base64 编码缺失 type 问题
galacean/appx-adapter pull request #4
Opened 2024-07-17 03:34 UTC by Sruimeng

2024-07-18 12:12 UTC, yiiqii requested changes

2024-07-18 12:12 UTC, yiiqii commented on src/core/blob.ts
> +  constructor (public readonly buffers: ArrayBuffer[], public readonly type: string = 'image/png') { }
这个改动怎么通过编译的？build 报错了
![image](https://github.com/user-attachments/assets/ac237267-73f3-4b64-9085-3ce135de17e2)

2024-07-19 03:16 UTC, Sruimeng commented on src/core/blob.ts
> +  constructor (public readonly buffers: ArrayBuffer[], public readonly type: string = 'image/png') { }
已修复

2024-07-19 03:22 UTC, yiiqii requested changes

2024-07-19 03:22 UTC, yiiqii commented on src/core/blob.ts
> +  constructor (public readonly buffers: ArrayBuffer[], public readonly type: string = 'image/png') { }
`public readonly type: string | Record<string, any> = 'image/png'`

2024-07-22 02:32 UTC, Sruimeng commented on src/core/blob.ts
> +  constructor (public readonly buffers: ArrayBuffer[], public readonly type: string = 'image/png') { }
已修复

2024-07-22 02:42 UTC, yiiqii requested changes

2024-07-22 02:42 UTC, yiiqii commented on src/core/url.ts
> +    const type = typeof blob.type === 'object' ? (blob.type as { type: string }).type : blob.type;
这个 as 就不用了

2024-07-22 03:27 UTC, Sruimeng commented on src/core/url.ts
> +    const type = typeof blob.type === 'object' ? (blob.type as { type: string }).type : blob.type;
已修复

2024-07-22 07:27 UTC, yiiqii approved these changes

2024-07-22 07:27 UTC, merged